### ISSUE TITLE
Feat: Carousel, desde una carpeta las imágenes en vez de una BD

### ISSUE THREAD

**Issue by ToniEsteso** [ToniEsteso/Grupo2-Cliente#1]
Carousel con imagenes sacadas de la base de datos

**Comment by JoseMiZome** [comment]
Arreglado carousel, no se quedaba bien, ahora ya está hecho, faltará cambiar los nombres de las imágenes y meterlas en la BD.

**Comment by JoseMiZome** [comment]
Falta arreglar el por qué no se muestran las imágenes, ya que pones la ruta en el navegador y funciona
