### ISSUE TITLE
Feat: componente menu

### ISSUE THREAD

**Issue by ToniEsteso** [ToniEsteso/Grupo2-Cliente#2]
Crear componente menu

**Comment by daviddelriocatalan** [comment]
En principio ya esta arreglado, le he quitado los textos de "menu principal" y "imagen usuario". Le he puesto a los menu__item la altura 100% para que ocupen el espacio que les da el menu. y he puesto una imagen png en la del usuario para tener una referencia visual de cuanto ocupará. Y he hecho un poco mas corta la barra de busqueda.
